
  
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1🌟',
    },
    {
      id: 2,
      value: '2',
      label: '2🌟',
    },
    {
      id: 3,
      value: '3',
      label: '3🌟',
    },
    {
      id: 4,
      value: '4',
      label: '4🌟',
    },
    {
      id: 5,
      value: '5',
      label: '5🌟',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      title: 'lounge resort',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '45-60min',
      deliveryFee: 3.44,
      category: 'place',
      cuisine: 'apartment',
      rating: 5,
      price: 2500,
      coverSrc: '/images/places/ameri.jpg',
    },
    {
      id: 2,
      title: 'Kings Inn',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '15-20min',
      deliveryFee: 4.94,
      category: 'place',
      cuisine: 'holiday',
      rating: 4,
      price: 1000,
      coverSrc: '/images/places/italian.webp',
    },
    {
      id: 3,
      title: 'Lustrio Inn',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '30-22min',
      deliveryFee: 4.94,
      category: 'place',
      cuisine: 'guest',
      rating: 3,
      price: 2000,
      coverSrc: '/images/places/china.jpg',
    },
    {
      id: 4,
      title: 'Moss View Hotel',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '10-18min',
      deliveryFee: 2.14,
      category: 'place',
      cuisine: 'resort',
      rating: 1,
      price: 1800,
      coverSrc: '/images/places/sea.jpg',
    },
    {
      id: 5,
      title: 'Omni Hotels',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '25-30min',
      deliveryFee: 6.79,
      category: 'place',
      cuisine: 'bnb',
      rating: 5,
      price: 2000,
      coverSrc: '/images/places/italiian.jpg',
    },
    {
      id: 6,
      title: 'Paramount Hotel',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '5-15min',
      deliveryFee: 2.87,
      category: 'place',
      cuisine: 'Resort',
      rating: 5,
      price: 3500,
      coverSrc: '/images/places/fookyew2.jpg',
    },
    {
      id: 7,
      title: 'Primland',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '50-65min',
      deliveryFee: 8.5,
      category: 'dish',
      cuisine: 'guest',
      rating: 2,
      price: 2200,
      coverSrc: '/images/places/img01.jpg',
    },
    {
      id: 8,
      title: 'Roadside',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '10-15min',
      deliveryFee: 1.8,
      category: 'dish',
      cuisine: 'holiday',
      rating: 1,
      price: 1900,
      coverSrc: '/images/places/img02.png',
    },
    {
      id: 9,
      title: 'Shitake Fried Rice',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '12-18min',
      deliveryFee: 3.33,
      category: 'dish',
      cuisine: 'apartment',
      rating: 4,
      price: 2750,
      coverSrc: '/images/places/img03.jpg',
    },
    {
      id: 10,
      title: ' Malibu',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '30-38min',
      deliveryFee: 1.9,
      category: 'dish',
      cuisine: 'holiday',
      rating: 2,
      price: 4350,
      coverSrc: '/images/places/img04.jpg',
    },
    {
      id: 11,
      title: 'Hillside Hotel',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '16-20min',
      deliveryFee: 4.1,
      category: 'dish',
      cuisine: 'bnb',
      rating: 3,
      price: 3300,
      coverSrc: '/images/places/img05.jpg',
    },
    {
      id: 12,
      title: 'Dim Sums',
      description:'This impressive paella is a perfect party dish and a fun meal to cook together with your guests.',
      serviceTime: '24-30min',
      deliveryFee: 1.5,
      category: 'dish',
      cuisine: 'Guest',
      rating: 2,
      price: 4100,
      coverSrc:'/images/places/img06.jpg',
    },
  ];
  